### ISSUE TITLE
custom_filters not recognized on elixir 1.15.0

### ISSUE THREAD

**Issue by BobbyMcWho** [edgurgel/solid#122]
Steps to reproduce: Run Solid.render, passing in a custom filters module
Expected: Custom filters are recognized in the template
Behavior: Solid.UndefinedFilterError is returned

**Comment by tayjohno** [comment]
I was also getting undefined filter errors after upgrading to Elixir 1.15. In my case I would only see these errors briefly initially, then they would stop. I was certain it was some sort of loading issue, and after stepping through some of the code, I found `Solid.Filter.filter_exists?/1` was returning `false` because on the `Kernel.function_exported?/3` check. This turned out to be because the module wasn't loaded.

Note below copied from [`Kernel.function_exported?/3`](https://hexdocs.pm/elixir/1.15/Kernel.html#function_exported?/3):
> Note that this function does not load the module in case it is not loaded. Check [Code.ensure_loaded/1](https://hexdocs.pm/elixir/1.15/Code.html#ensure_loaded/1) for more information.

I think this could be fixed with a simple patch like below.

```elixir
defp filter_exists?({module, function, arity}) do
    try do
      function = String.to_existing_atom(function)
      {:module, module} = Code.ensure_loaded(module) # FIX
      function_exported?(module, function, arity)
    rescue
      ArgumentError -> false
    end
  end
```

For anyone else running into this, looking for a quick solution, you can put that same patch right before calling Solid:

```elixir
  defp do_render(template, data, opts) do
    filters = Code.ensure_loaded!(Filters)
    Solid.render!(template, data, Keyword.merge(opts, custom_filters: filters))
  end
```

**Comment by edgurgel** [comment]
Solved by https://github.com/edgurgel/solid/pull/132
